---
title: "Kriging"
subtitle: "CMDA 4654 Project 2 - Group 1"
author: "Baker Dean, Toshaani Dewan?, Nick Fitti, Nico Ottobre, Margaret Smith"
date: "22nd April, 2026"
fontsize: 10pt
classoption: "aspectratio=169"
output: 
  beamer_presentation: 
    fonttheme: professionalfonts
    highlight: kate
    theme: default
urlcolor: blue
header-includes:
- \definecolor{VTmaroon}{HTML}{861F41}
- \usecolortheme[named=VTmaroon]{structure}
- \usepackage{booktabs}
- \usepackage{longtable}
- \usepackage{array}
- \usepackage{multirow}
- \usepackage{wrapfig}
- \usepackage{float}
- \usepackage{colortbl}
- \usepackage{pdflscape}
- \usepackage{tabu}
- \usepackage{threeparttable}
- \usepackage{threeparttablex}
- \usepackage[normalem]{ulem}
- \usepackage{makecell}
- \usepackage{xcolor}
- \usepackage{bbm}
- \usepackage{cancel}
- \usepackage{amsmath}
- \usepackage{amssymb}
- \usepackage{bm}
- \usepackage{enumitem}
- \usepackage{underscore}
---
```{r setup, include=FALSE}
library(knitr)
library(dplyr)
library(ggplot2)
library(hoopR)
library(progressr)
library(gstat)
library(sp)
library(automap)
library(patchwork)
library(scales)

knitr::opts_chunk$set(echo = FALSE,
                      comment = NA,
                      message = FALSE,
                      warning = FALSE,
                      fig.align = "center")

def.chunk.hook <- knitr::knit_hooks$get("chunk")
knitr::knit_hooks$set(chunk = function(x, options) {
  x <- def.chunk.hook(x, options)
  paste0("\n \\", "footnotesize","\n\n", x, "\n\n \\normalsize")
})
```

## Kriging Intro 

Why use Kriging? \
- discuss spatial statistics

Example ... \
- Read and look for a real life example... different than the contexts used as our real examples


## Kriging - Overview

\begin{columns}
\begin{column}{0.55\textwidth}

\underline{Goal:} \\
- estimate data values $Z^*(x_0)$ at unknown locations based on the given data $Z(x_i)$, for $i = 1, \dots, n$. 
\vspace{1.5em}

\underline{Assumption:} \\
- An observation will be more similar to data that is "close" in space comparative to those "far" in space.
\vspace{1.5em}

"Closeness" will be determined by the spatial correlation between points in the given field of data.

\end{column}
\begin{column}{0.45\textwidth}

*Need to insert a dummy picture of points in space to reference when talking about the known points vs the unknown prediction points of interest*

\end{column}
\end{columns}





## The Kriging Model

\underline{Generic Model:}
\begin{align*}
Z(x) &= \mu(x) + \epsilon(x)  \\
\epsilon(x) &\sim \mathcal{N}(0, \sigma^2) \end{align*}

*Notation:* \
- $Z(x)$ is the variable of interest (e.g. zinc concentration) at location $x$. \
- $\mu(x)$ is the mean response at location $x$ \
- $\epsilon(x)$ is the residual of the response at location $x$



## "Closeness"

- Discuss variogram
- Bullet 2
- Bullet 3

##

Another slide...


## Sources
